import type { Category, Product } from "@/types";

export const homepageCategories: Category[] = [
  {
    id: "batik-pria",
    name: "Batik Pria",
    slug: "batik-pria",
    description: "Kemeja dan atasan batik dengan potongan modern.",
  },
  {
    id: "batik-wanita",
    name: "Batik Wanita",
    slug: "batik-wanita",
    description: "Dress dan blouse batik yang anggun dan nyaman.",
  },
  {
    id: "outer-batik",
    name: "Outer Batik",
    slug: "outer-batik",
    description: "Outer dan luaran batik untuk layering kasual.",
  },
];

export const homepageProducts: Product[] = [
  {
    id: "batik-kawung-arunika",
    name: "Batik Kawung Arunika",
    slug: "batik-kawung-arunika",
    description: "Kemeja batik pria motif kawung klasik dengan palet hangat modern.",
    price: 349000,
    stock: 24,
    category_id: "batik-pria",
    image_url: null,
    is_featured: true,
    category: "Batik Pria",
    badge: "Terlaris",
  },
  {
    id: "batik-sekar-jagad-laras",
    name: "Batik Sekar Jagad Laras",
    slug: "batik-sekar-jagad-laras",
    description: "Dress batik wanita motif sekar jagad yang mewah.",
    price: 459000,
    stock: 15,
    category_id: "batik-wanita",
    image_url: null,
    is_featured: true,
    category: "Batik Wanita",
    badge: "Baru",
  },
  {
    id: "batik-parang-senja",
    name: "Batik Parang Senja",
    slug: "batik-parang-senja",
    description: "Kemeja batik pria motif parang dengan gradasi warna senja.",
    price: 289000,
    stock: 32,
    category_id: "batik-pria",
    image_url: null,
    is_featured: false,
    category: "Batik Pria",
  },
  {
    id: "outer-batik-senja-kirana",
    name: "Outer Batik Senja Kirana",
    slug: "outer-batik-senja-kirana",
    description: "Outer batik unisex untuk layering kasual.",
    price: 399000,
    stock: 20,
    category_id: "outer-batik",
    image_url: null,
    is_featured: true,
    category: "Outer Batik",
    badge: "Baru",
  },
];
